
services:
  dev-app:
    build:
      context: ..

    ports:
      - 8000:8000

    volumes:
      - ..:/src

    command: >
      sh -c "uvicorn --factory app.main:create_app --reload --host 0.0.0.0 --port 8000"
